const internalUrl = (url: string, base: string) => { const m = /connected\.wildflowerschools\.org\/(posts|series|questions)\/(\d+)/.exec(url); return m ? `${base}/c/${m[1] === "posts" ? "post" : m[1] === "series" ? "series" : "question"}/${m[2]}` : url; };
import type { ReviewResult } from "@wfw/shared";
import { env } from "../env.js";

const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
export function reviewToHtml(title: string, typeName: string, r: ReviewResult, appUrl: string): string {
  const li = (xs: string[]) => xs.map((x) => `<li>${esc(x)}</li>`).join("");
  return `<div style="font-family:Avenir Next,Avenir,Helvetica Neue,Arial,sans-serif;color:#294844;max-width:680px;line-height:1.5">
  <h1 style="font-family:Garamond,Times New Roman,serif;color:#137070;font-weight:500">Feedback on ${esc(title)}</h1>
  <p style="color:#566c66">Material type: ${esc(typeName)} · Verdict: <strong>${esc(r.verdict)}</strong></p>
  <p style="background:#e1f3f0;padding:12px;border-radius:8px"><strong>If you fix one thing:</strong> ${esc(r.one_thing)}</p>
  <p>${esc(r.summary)}</p>
  <h2 style="font-family:Garamond,serif;color:#137070;font-weight:500">Objectives</h2>
  <table style="border-collapse:collapse;width:100%">${r.rubric.map((c) => `<tr><td style="padding:6px;border-bottom:1px solid #cbdad4"><strong>${esc(c.criterion)}</strong></td><td style="padding:6px;border-bottom:1px solid #cbdad4;text-align:center">${c.score}/5</td><td style="padding:6px;border-bottom:1px solid #cbdad4">${esc(c.note)}</td></tr>`).join("")}</table>
  <h2 style="font-family:Garamond,serif;color:#137070;font-weight:500">What is working</h2><ul>${li(r.strengths)}</ul>
  <h2 style="font-family:Garamond,serif;color:#137070;font-weight:500">Priority changes</h2>${r.priority_changes.map((p) => `<p><strong>${esc(p.what)}</strong><br>${esc(p.why)}<br><em>How:</em> ${esc(p.how)}</p>`).join("")}
  <h2 style="font-family:Garamond,serif;color:#137070;font-weight:500">Line notes</h2>${r.line_notes.map((n) => `<p><q style="color:#566c66">${esc(n.quote)}</q><br>${esc(n.note)}</p>`).join("")}
  ${r.example_rewrites.length ? `<h2 style="font-family:Garamond,serif;color:#137070;font-weight:500">Example rewrites (one option, not a replacement)</h2>${r.example_rewrites.map((e) => `<p><em>Original:</em> ${esc(e.original)}<br><em>Option:</em> ${esc(e.rewrite)}<br><span style="color:#566c66">${esc(e.why)}</span></p>`).join("")}` : ""}
  ${r.questions_for_writer.length ? `<h2 style="font-family:Garamond,serif;color:#137070;font-weight:500">Questions for you</h2><ul>${li(r.questions_for_writer)}</ul>` : ""}
  ${r.verify_with_humans.length ? `<h2 style="font-family:Garamond,serif;color:#795600;font-weight:500">Verify with your Operations Guide, attorney, or accountant</h2><ul>${li(r.verify_with_humans)}</ul>` : ""}
  ${r.recommended_resources.length ? `<h2 style="font-family:Garamond,serif;color:#137070;font-weight:500">Resources to use</h2><ul>${r.recommended_resources.map((x) => `<li><a href="${esc(internalUrl(x.url, appUrl))}" style="color:#137070">${esc(x.title)}</a> — ${esc(x.why)}</li>`).join("")}</ul>` : ""}
  ${r.nits.length ? `<h2 style="font-family:Garamond,serif;color:#137070;font-weight:500">Nits</h2><ul>${li(r.nits)}</ul>` : ""}
  <p style="color:#566c66;font-size:.85rem;margin-top:24px">Sent from <a href="${esc(appUrl)}" style="color:#137070">Wildflower Wisdom</a>. This feedback was generated by an AI reviewer using Wildflower's guidance; it is a starting point, not a decision.</p></div>`;
}
export function reviewToMarkdown(title: string, typeName: string, r: ReviewResult): string {
  const L = (xs: string[]) => xs.map((x) => `- ${x}`).join("\n");
  return `# Feedback on ${title}\n\nMaterial type: ${typeName}\nVerdict: **${r.verdict}**\n\n**If you fix one thing:** ${r.one_thing}\n\n${r.summary}\n\n## Objectives\n${r.rubric.map((c) => `- **${c.criterion}** ${c.score}/5: ${c.note}`).join("\n")}\n\n## What is working\n${L(r.strengths)}\n\n## Priority changes\n${r.priority_changes.map((p) => `### ${p.what}\n${p.why}\n\nHow: ${p.how}`).join("\n\n")}\n\n## Line notes\n${r.line_notes.map((n) => `> ${n.quote}\n\n${n.note}`).join("\n\n")}\n\n${r.example_rewrites.length ? `## Example rewrites (one option, not a replacement)\n${r.example_rewrites.map((e) => `Original: ${e.original}\n\nOption: ${e.rewrite}\n\n${e.why}`).join("\n\n")}\n\n` : ""}${r.questions_for_writer.length ? `## Questions for you\n${L(r.questions_for_writer)}\n\n` : ""}${r.verify_with_humans.length ? `## Verify with your Operations Guide, attorney, or accountant\n${L(r.verify_with_humans)}\n\n` : ""}${r.recommended_resources.length ? `## Connected resources\n${r.recommended_resources.map((x) => `- [${x.title}](${x.url}) — ${x.why}`).join("\n")}\n\n` : ""}${r.nits.length ? `## Nits\n${L(r.nits)}\n` : ""}`;
}
export async function sendEmail(to: string, subject: string, html: string, replyTo?: string): Promise<{ id: string }> {
  if (!env.resendKey) throw new Error("RESEND_API_KEY is not set");
  const r = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${env.resendKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ from: env.mailFrom, to: [to], subject, html, ...(replyTo ? { reply_to: replyTo } : {}) }) });
  if (!r.ok) throw new Error(`Resend failed: ${r.status} ${(await r.text()).slice(0, 200)}`);
  return await r.json() as { id: string };
}
